### ISSUE TITLE
'start-display' stops working and screens go dark - priority 1

### ISSUE THREAD

**Issue by taylorlm88** [JaneliaSciComp/G4_Display_Tools#21]
Summary: The ‘start_display’ command does not always start the LED panels. When this happens the event is also not logged in the TDMS file.

Description: Some combination of ‘start_display’ (0x03 0x21 0xNN 0xNN) and ‘stop_display’ (0x01 0x30) leads to the situation that ‘start_display’ does not work anymore. ‘Not work’ means, that the physical LED panels don’t switch on anymore but remain dark. The instance this happens, the logging also ignores incoming commands: whenever the TDMS files are finalized with the ‘stop_log’ command (0x01, 0x40), the ‘Start Display’ events are logged in ‘Commands Received’ data structure of the TDMS file for the times the display was turned on, but not for the ‘start_display’ commands when the panels remained dark. The expected result is that ‘start_display’ always turns the LED on and does not depend on an internal state of the system.

The reproducibility of the error depends on unknown circumstances. On at least two of our systems, the following code reproduces the error with a high probability: running the script once usually leads to dark panels for the ‘start_display’ command around the 20th loop. On some occasions the script needed to run a few times before the error happened. On one specific system last summer we were able to reproduce the error each single time by choosing the duration for the ‘start_display’ command shorter than the following pause until the next ‘start_display’ command was sent, but we cannot reproduce that special case right now. Just looking at the TDMS file, the error can be replicated without an attached arena.

Potentially this is a timing issue and the ‘start_display’ command is masked by the preceding ‘stop_display’ command. But even in that case, the commands should be logged in the TDMS file or the Main Host needs to report an error back to the client.

test4.m, found at https://gist.github.com/floesche/874531bf83aba604a747d9d92e7bca68 replicates the error. Find code below: 

```matlab

%% script to demonstrate a problem
%%
%% Problem 1: all-black (< 0.2sec) between different pauses, most often between 1 and 2, 5 and 6.
%% Problem 2: Stop log is not received unless there is an additional pause just before that. Why is the host not available then?


connectHost;

Panel_com('change_root_directory', 'C:\matlabroot\G4');
Panel_com('start_log');

Panel_com('set_control_mode',1);
Panel_com('set_pattern_id', 1);

counter = 0;

%% 
for i = 1:100
    counter = counter + 1;    
    Panel_com('start_display', 0.5);
    disp("pause " + counter + " started");
    pause(0.5);
    disp("pause over");
    Panel_com('stop_display');
end

%% This doesn't work at all. I always need to stop log manually...
pause(5)
Panel_com('stop_log');
disconnectHost;

```

**Comment by taylorlm88** [comment]
An update to this issue - it happens particularly in mode 1. However, if we connect the host and preview a pattern in mode 3, streaming mode, then proceed to submit mode 1 parameters, this issue does not happen. We discovered this with the Designer's preview and dry run features. If you open an experiment and do a dry run of a single mode 1 trial (meaning you run that full trial on the screens in isolation), after it is over, the Host will not receive anymore Panel_com commands. Too much time has passed since the start display. 

However,  if you open an experiment and click "Preview Arena" and click on a single pattern, this displays that pattern in mode 3. Meaning it will continue displaying until you submit new Panel_com parameters. If you do this first, you can then do as many dry runs and pattern previews as you like and the Host never stops receiving the panel_com commands. 

This can all be duplicated by hand manually submitting Panel_com commands. It seems like the FIRST time something is displayed on the arena, if it is mode 1, then this bug occurs. If more time passes from the 'start-display' command to the next start-display command than is passed in, all the panel_com commands stop being received. But if mode 3 is used first, which does not use a start-display command, then the bug is not an issue.

**Comment by floesche** [comment]
If this turns out to be a timing issue, maybe #22 is somehow related?

**Comment by floesche** [comment]
response via email:

> I took a look at the first issue #21 and noticed some odd timing when receiving the commands from Matlab. I basically ran the `test4.m` script shown below and noticed the time when I received a command was not consistent with the supposed timing of when Matlab is sending the command. I should basically be seeing a command every 500ms, but it seems to backlog a bit and then send a bunch of commands. The first two graphs show the time messages are received from the TCP port. The Y axis is in seconds and is showing an odd value because it was converted from ticks, but you can see the relative timing between the messages.
>
> I also wrote the equivalent LabVIEW version of the matlab script and the third graph shows the consistent timing of when the software is receiving the message so there is something going on with the Matlab TCP interface. Fixing this might not solve all the issues, but it is definitely not what it should be doing.
>
>```matlab
>%% test4.m script to demonstrate a problem
>%%
>%% Problem 1: all-black (< 0.2sec) between different pauses, most often between 1 and 2, 5 and 6.
>%% Problem 2: Stop log is not received unless there is an additional pause just before that. Why is the host not available then?
>
>connectHost;
>
>Panel_com('change_root_directory', 'C:\matlabroot\G4');
>Panel_com('start_log');
>
>Panel_com('set_control_mode',1);
>Panel_com('set_pattern_id', 1);
>
>counter = 0;
>
>%%
>for i = 1:100
>    counter = counter + 1;    
>    Panel_com('start_display', 0.5);
>    %disp("pause " + counter + " started");
>    pause(0.5);
>    %   disp("pause over");
>    Panel_com('stop_display');
>end
>
>%% This doesn't work at all. I always need to stop log manually...
>pause(5)
>Panel_com('stop_log');
>pause(1)
>% disconnectHost;
>```

![thumbnail_image](https://user-images.githubusercontent.com/1568893/160133203-b8e1f8b6-d734-46ae-9feb-b4c3a834bc86.png)
![thumbnail_image 85](https://user-images.githubusercontent.com/1568893/160133229-70640319-e87a-4a5a-9a61-6cc07186e9b5.png)

**Comment by floesche** [comment]
For the figure below I went the opposite direction: I kept the test4.m script "as is" (copy & pasted from this email) but replaced the "G4 Host.exe" with a mock script written in Python (see attached "mock_main_host.py"). This shows that without the "G4 Host.exe" the timing of the MATLAB script test4.m (and therefore Panel_com) is excellent. The error only happens when the messages are sent to the webserver run by "G4 Host.exe".

The following plot shows the logged timestamps for 11 repetitions of the experiment: it's very consistent timing, they are almost exact overlays. If you look at the raw data (also attached) you will see differences in the ms range, not in the second range as in your plots.

![index](https://user-images.githubusercontent.com/1568893/160133743-9072938b-74c2-4294-8b71-b2ec83415ae5.png)

 The python script starts a web server on the port usually occupied by "G4 Host.exe", listens to incoming messages, logs them with nanosecond precision, and echoes the message back. The script stops when a "stop log" command is received.

If the script runs before test4.m the timestamp, command ID, and the whole TCP message are logged in "conn.csv". If the script does not run, then MATLAB starts "G4 Host.exe" (or uses an already open one) without any further code changes. This allows a direct comparison.

I alternated between "mock_main_host.py" and "G4 Host.exe" on my system and was able to reproduce the documented error as well as (error free) logging shown below.


To keep track of the issue and potential solutions I will copy these emails (after removing email addresses and other personal information) to the GitHub issue #21 unless there is an issues with that?

I am wondering as well if there is some fundamental issues with the communication. Since "start display" is involved, do you think there is some overlap with the issue documented in #59 (I just came across this a few days ago)?

**Comment by floesche** [comment]
For the figure below I went the opposite direction: I kept the `test4.m` script "as is" (copy & pasted from above) but replaced the `G4 Host.exe` with a mock script written in Python (see below `mock_main_host.py`). This shows that without the `G4 Host.exe` the timing of the MATLAB script `test4.m` (and therefore `Panel_com`) is excellent. The error only happens when the messages are sent to the webserver run by `G4 Host.exe`.

The following plot shows the logged timestamps for 11 repetitions of the experiment: it's very consistent timing, they are almost exact overlays. If you look at the raw data (also attached) you will see differences in the ms range, not in the second range as in your plots.

![index](https://user-images.githubusercontent.com/1568893/160133743-9072938b-74c2-4294-8b71-b2ec83415ae5.png)

The python script starts a web server on the port usually occupied by `G4 Host.exe`, listens to incoming messages, logs them with nanosecond precision, and echoes the message back. The script stops when a `stop log` command is received.

If the script runs before `test4.m` the timestamp, command ID, and the whole TCP message are logged in `conn.csv`. If the script does not run, then MATLAB starts `G4 Host.exe` (or uses an already open one) without any further code changes. This allows a direct comparison.

I alternated between `mock_main_host.py` and `G4 Host.exe` on my system and was able to reproduce the documented error as well as (error free) logging shown below.

I am wondering as well if there is some fundamental issues with the communication. Since `start display` is involved in the `test4.m` script, do you think there is some overlap with the issue documented in #59 (I just came across this a few days ago)?

```python
# mock_main_host.py
import socket
import csv
import time

HOST = "127.0.0.1"  # Standard loopback interface address (localhost)
PORT = 62222  # Port to listen on (non-privileged ports are > 1023)

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s, open('conn.csv', 'w', newline='') as csvfile:
    logwriter = csv.writer(csvfile)
    s.bind((HOST, PORT))
    s.listen()
    conn, addr = s.accept()
    logwriter.writerow(["ts", "cmd", "tcp"])
    with conn:
        print(f"Connected by {addr}")
        while True:
            data = conn.recv(1024)
            if not data:
                break

            logwriter.writerow([time.time_ns(), data[1], data])           
            
            conn.sendall(data)
            if(data[1] == 64):
                break
```

[01_conn.csv](https://github.com/JaneliaSciComp/G4_Display_Tools/files/8351070/01_conn.csv)
[02_conn.csv](https://github.com/JaneliaSciComp/G4_Display_Tools/files/8351083/02_conn.csv)
[03_conn.csv](https://github.com/JaneliaSciComp/G4_Display_Tools/files/8351084/03_conn.csv)
[04_conn.csv](https://github.com/JaneliaSciComp/G4_Display_Tools/files/8351085/04_conn.csv)
[05_conn.csv](https://github.com/JaneliaSciComp/G4_Display_Tools/files/8351086/05_conn.csv)
[06_conn.csv](https://github.com/JaneliaSciComp/G4_Display_Tools/files/8351087/06_conn.csv)
[07_conn.csv](https://github.com/JaneliaSciComp/G4_Display_Tools/files/8351088/07_conn.csv)
[08_conn.csv](https://github.com/JaneliaSciComp/G4_Display_Tools/files/8351089/08_conn.csv)
[09_conn.csv](https://github.com/JaneliaSciComp/G4_Display_Tools/files/8351090/09_conn.csv)
[10_conn.csv](https://github.com/JaneliaSciComp/G4_Display_Tools/files/8351091/10_conn.csv)
[11_conn.csv](https://github.com/JaneliaSciComp/G4_Display_Tools/files/8351092/11_conn.csv)

**Comment by floesche** [comment]
Response via email:

> So I had to refresh my memory on how things were working before and I think the problem is the way we are using the "Stop Display" command. This command will wait for all the remaining frames to be played out in the DMA and then stop updating the display completely. If you know the duration of how long you want a pattern to be played out then you should set the duration in the "Start Display" command and once it finishes, it will automatically switch to stream mode and continuously send the last frame (this should prevent blank frames in between different patterns). Also, I do send back a response when the "Start-Display" command has finished sending all the frames so you can wait for that instead of just doing a pause if you want.
>
>
>```matlab
> Panel_com('start_log');
>
>Panel_com('set_control_mode',1);    
>Panel_com('set_pattern_id', 1);
>
>counter = 0;
>
>%%
>for i = 1:100
>    counter = counter + 1;    
>    Panel_com('start_display', 0.5);
>    disp("pause " + counter + " started");
>    pause(0.5);
>    disp("pause over");
>
>end
>
>pause(5)
>Panel_com('stop_log');
>pause(1)
>```
> 
>
>If you don't know how long you want a pattern to play out then you can set the duration to something very long and then send a "Control Mode" command set to "Stream" to stop the display and continuously display the last frame. Then you can switch your control mode back to what you were using before when you are ready to start it again.
>
>```matlab
>Panel_com('start_log');
>
>Panel_com('set_control_mode',1);    
>Panel_com('set_pattern_id', 1);
>
>counter = 0;
>
>%%
>for i = 1:100
>    counter = counter + 1;    
>    Panel_com('set_control_mode',1);  
>    Panel_com('start_display', 100);
>    disp("pause " + counter + " started");
>    pause(0.5);
>    disp("pause over");
>   Panel_com('set_control_mode',0);
>
>    pause(2);
>end
>
>pause(5)
>Panel_com('stop_log');
>pause(1)
>```

**Comment by floesche** [comment]
We’ll discuss and send back further comments or questions if they come up.

In the meantime, I’d like to make sure that I am following your suggestion…basically it is to avoid using `stop_display` at all if we’re going to be rapidly presenting one pattern after another?

So the proposal is that if we just use `set_control_mode, 0` wherever we had previously used `stop_display` we should not see this problem?

Please confirm. In this case I have a few follow up questions:

1. What functionality does `stop_display` offer over your suggestion to change the control mode to 0? Does `stop display` ensure that # of frames expected based on the duration (set w. `start_display`) are shown, or just whatever frames are in the DMA buffer, which could depend on exactly when the `stop_display` command is received.
2. Based on your testing script (the first one), is there any problem with issuing a series of `start_display` commands (here with a pause in between them) without either `stop_display` or the change in control mode?
3. While your 2 examples show a way to avoid this one bug, for a reliable operation and not too much ‘dead’ time – do you agree that waiting for the response from the `start-display` command would be the most reliable way to use this?

**Comment by floesche** [comment]
Response (via email):

>> So the proposal is that if we just use ‘set_control_mode’, 0 wherever we had previously used `stop_display` we should not see this problem?
>
>Yes, I would avoid using `stop_display` unless you actually want to stop updating the arena. I think you can get away with not sending a `set_control_mode` command at all if you set the duration on the `start_display` command properly. But if you do need to stop it then I would use `set_control_mode` to `0` and then switch it back to the mode you were using previously when you are ready to start again.

---
>>1. What functionality does `stop_display` offer over your suggestion to change the control mode to 0? 
>
> The `stop_display` will stop updating the arena so it will be blank. 
>
>> Does `stop display` ensure that # of frames expected based on the duration (set w. `start_display`) are shown, or just whatever frames are in the DMA buffer, which could depend on exactly when the `stop_display` command is received. 
>
>The second one.
>
>>2. Based on your testing script (the first one), is there any problem with issuing a series of ‘start_display’ commands (here with a pause in between them) without either ‘stop_display’ or the change in control mode? 
>
> I haven't run it on an arena, but software wise it does it without any issue.
>
>>3. While your 2 examples show a way to avoid this one bug, for a reliable operation and not too much ‘dead’ time – do you agree that waiting for the response from the ‘start-display’ command would be the most reliable way to use this? 
>
>Waiting for a response will definitely ensure that all the frames will have been played out for the duration time you set, but there may be a little latency between the time you receive it and send the next command. In the future, maybe I can do a buffered command list so there is no delay between different start times.

**Comment by floesche** [comment]
Thanks for the response and figuring this out. We talked about the suggestion and can avoid the `stop_display​` command in our experiments for now.

You confirmed that the most reliable solution for the the `start_display`​ command would be to wait for the response from the controller – which is also our preference (to avoid having two separate clocks etc…). At the moment that doesn't seem to work reliably because the response time is sometimes considerably different from the expected timing (see details of our measurements in issue #59). Could you please have a look at this related issue and see if you can replicate that?

**Comment by floesche** [comment]
(response via email 2022-04-04T14:24):
> I suggested waiting for the return message for when completed. I also suggested sending control mode 0 when stopping the 'start-display' run prematurely. I did realize that doing that will cause a reconfiguration of the FIFO size (there are two different size FIFOs, one for stream and non-stream mode) which could cause a blank display. I disabled that reconfiguration and will just be using the stream FIFO size. The initial intent was to have a larger FIFO size for modes where latency wasn't as big of a deal and having a larger FIFO is a bit safer to prevent possible overrun, but I think the software can probably run fine on the smaller FIFO size that is used in stream mode.

latest [G4 Host-v1.0.0.237](https://www.dropbox.com/s/53foh65h6akxhqk/G4%20Host%28Ver1-0-0-237%29.zip?dl=0) ([GitHub mirror](https://github.com/floesche/LED-Display_G4_Display-Tools/releases/download/host-v235/G4.Host.Ver1-0-0-237.zip))

**Comment by floesche** [comment]
(response via email 2022-04-07T16:47):
> I forgot to remove some debugging that can grow infinitely when receiving tcp commands. Here is the version [238](https://www.dropbox.com/s/n27hlx5i6knab96/G4%20Host%28Ver1-0-0-238%29.zip?dl=0) ([GitHub mirror](https://github.com/floesche/LED-Display_G4_Display-Tools/releases/download/host-v235/G4.Host.Ver1-0-0-238.zip)) with it removed.
