### ISSUE TITLE
Conductor shows wrong AO Function ID

### ISSUE THREAD

**Issue by floesche** [JaneliaSciComp/G4_Display_Tools#79]
When running an experiment in the Experiment Conductor with a trial that has AO2=1 and AO4=2, the conductor shows this:

![image](https://github.com/JaneliaSciComp/G4_Display_Tools/assets/1568893/012a5526-33a7-4ba0-8c1b-ede52ffa0cc1)

**Comment by taylorlm88** [comment]
Tried this out today and I saw the correct id numbers for the AO functions - this may have been fixed with the big update we did a few weeks ago. I ran an experiment on the updated version with AO2 = 1 and AO4 = 2 during the block trials and another with AO2 = 3, AO3 = 2, and AO4 = 1 during the intertrial. This led me to discover an issue with running AO functions in the intertrial, but I fixed that. The Conductor showed the correct IDs though. If this issue happens again could you include the exact experiment used so I can investigate why it might happen with that particular experiment? 

<img width="878" alt="Screenshot 2023-10-01 at 3 13 23 PM" src="https://github.com/JaneliaSciComp/G4_Display_Tools/assets/45794967/ff3fdc85-212f-4ef0-91dc-e3305eb71b11">

<img width="876" alt="Screenshot 2023-10-01 at 3 13 31 PM" src="https://github.com/JaneliaSciComp/G4_Display_Tools/assets/45794967/dbc953db-e66f-4b54-9a02-62f88c186585">
